config/routes.rb
RailsPrelaunchSignup::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :shots
  resources :upload, :only => [:show, :index] 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/shot.rb
class Shot < ActiveRecord::Base
  belongs_to :user
  has_attached_file :photo, :url => "/assets/:id/:basename.:extension",
  :path => ":rails_root/public/assets/:id/:basename.:extension"
  attr_accessible :title, :photo, :user_id, :alert, :index
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shots
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at, :user_id
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  def show
     @shot = Shot.find(params[:id])
   end
   
  def edit
    @shot = Shot.find(params[:id])
  end
  
  def create
    @shot = Shot.new(params[:shot])
    @shot.user_id = current_user.id
    if @shot.save
      redirect_to :back, :notice => "Shot was uploaded successfully!"
    else
      redirect :back, :alert => "It didn't work."
    end
  end
  
  def destroy
    @shot = Shot.find(params[:id]) 
    @shot.destroy 
    redirect_to :back, :notice => "Shot was deleted!"
  end
   
  def update
     @shot = Shot.find(params[:id])

     respond_to do |format|
       if @shot.update_attributes(params[:shot])
         format.html { redirect_to @shot, notice: 'Shot was successfully updated.' }
         format.json { head :no_content }
       else
         format.html { render action: "edit" }
         format.json { render json: @shot.errors, status: :unprocessable_entity }
       end
     end
   end
  
end

app/controllers/upload_controller.rb
class UploadController < ShotsController
  class UsersController < ApplicationController
    before_filter :authenticate_user!

    def index
      authorize! :index, @user, :message => 'Not authorized as an administrator.'
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
      @shots = @user.shots
      @shot = Shot.new
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @shots = @user.shots
    @shot = Shot.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/layouts/_navigation.html.haml
= link_to "tattu", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
    %li
      = link_to('Upload Shot', destroy_user_session_path)
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
    - if current_user.has_role? :admin
      %li
        = link_to('Admin', users_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "tattu"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer

app/views/shots/edit.html.erb
<%= form_for @shot do |form| %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

app/views/shots/index.html.erb
<%= form_for(@shot, :html => { :multipart => true }) do |form| %>
  <%= form.file_field :photo %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

<ul>
  <% @shots.each do |shot| %>
  <li><%= link_to shot.title, shot_path(shot) %></li>
  <li><%= link_to image_tag(shot.photo.url(:medium)), shot_path(shot) %></li>
  <li><%= link_to 'Edit', edit_shot_path(shot) %> or <%= link_to "Delete", shot_path(shot), :confirm => "Are you sure?", :method => :delete %>
  <% end %>
</ul> 

app/views/shots/show.html.erb
<ul>
<li><h1><%= @shot.title %></h1></li>
<li><%= image_tag @shot.photo.url(:medium) %></li>
</ul>

app/views/upload/index.html.erb
<p>User: <%= @user.name %> </p>
<p>Email: <%= @user.email if @user.email %></p>
<h1>Upload Shot:</h1>
<br />

<%= form_for(@shot, :html => { :multipart => true }) do |form| %>
  <%= form.file_field :photo %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

<ul>
  <% @shots.each do |shot| %>
  <li><%= link_to shot.title, shot_path(shot) %></li>
  <li><%= link_to image_tag(shot.photo.url(:medium)), shot_path(shot) %></li>
  <li><%= link_to 'Edit', edit_shot_path(shot) %> or <%= link_to "Delete", shot, :method => :delete %>
  <% end %>
</ul> 

<% if @shots.empty? %>
  <em>This user hasn't uploaded any shots! :(</em>
<% end %>

app/views/users/index.html.haml
%h2 Users
- @users.each do |user|
  %br/
  #{link_to user.email, user} signed up #{user.created_at.to_date}

app/views/users/show.html.erb
<p>User: <%= @user.name %> </p>
<p>Email: <%= @user.email if @user.email %></p>
<h1>Upload Shot:</h1>
<br />

<%= form_for(@shot, :html => { :multipart => true }) do |form| %>
  <%= form.file_field :photo %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

<ul>
  <% @shots.each do |shot| %>
  <li><%= link_to shot.title, shot_path(shot) %></li>
  <li><%= link_to image_tag(shot.photo.url(:medium)), shot_path(shot) %></li>
  <li><%= link_to 'Edit', edit_shot_path(shot) %> or <%= link_to "Delete", shot, :method => :delete %>
  <% end %>
</ul> 

<% if @shots.empty? %>
  <em>This user hasn't uploaded any shots! :(</em>
<% end %> 